name: build test deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - name: install dependencies
      run: npm install
    - name: install playwright
      run: npx playwright install
    - name: start backend
      run: npm run start-be &
    - name: wait 5 sec.
      run: sleep 5
    - name: start frontend
      run: npm run start-fe &
    - name: wait 5 sec.
      run: sleep 5
    - name: start integration tests
      run: npm run test
    
  deploy-backend:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.SERVICE_ID }}
        api-key: ${{ secrets.RENDER_TOKEN }}

  deploy-frontend:
    needs: deploy-backend
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to production
      uses: johnbeynon/render-deploy-action@v0.0.8
      with:
        service-id: ${{ secrets.FRONTEND_ID }}
        api-key: ${{ secrets.RENDER_TOKEN }}

